RegisterNetEvent('jms_crafting:startAdminPlacement', function(benchType, model)
    JMSPlacement.Start(model, function(coords, heading)
        TriggerServerEvent('jms_crafting:confirmAdminBench', benchType, coords, heading)
    end, function()
        lib.notify({ description = 'Bench placement cancelled.', type = 'inform' })
    end)
end)

RegisterNetEvent('jms_crafting:startAdminEdit', function(benchId, benchType, model)
    JMSPlacement.Start(model, function(coords, heading)
        TriggerServerEvent('jms_crafting:confirmAdminBenchEdit', benchId, coords, heading)
    end, function()
        lib.notify({ description = 'Bench edit cancelled.', type = 'inform' })
    end)
end)
